---
- name: Install the nginx package
  apt: name=nginx state=present
  become: yes

- name : Create web root directory
  file:
    path: /var/www/test
    state: directory
    mode: 0755

- name: Copy custom index.html file
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode : 0644

- name: start the nginx service
  systemd: name=nginx state=started enabled=yes 
